"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Guardian = { id: string; name: string; phone: string | null; relationship: string | null };
export default function GuardiansPage() {
  const [guardians, setGuardians] = useState<Guardian[]>([]); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [relationship, setRelationship] = useState(""); const [message, setMessage] = useState("");
  const load = async () => { const db = createClient(); const { data } = await db.from("guardians").select("id,name,phone,relationship").order("created_at"); setGuardians(data ?? []); };
  useEffect(() => { void load(); }, []);
  async function add() { const db = createClient(); const { data: { user } } = await db.auth.getUser(); if (!user || !name.trim()) return setMessage("Enter a Guardian name."); const { error } = await db.from("guardians").insert({ owner_id: user.id, name: name.trim(), phone: phone.trim() || null, relationship: relationship.trim() || null }); if (error) return setMessage(error.message); setName(""); setPhone(""); setRelationship(""); setMessage("Guardian added."); void load(); }
  async function remove(id: string) { await createClient().from("guardians").delete().eq("id", id); void load(); }
  return <div className="max-w-[640px] space-y-5"><div><p className="eyebrow">Emergency dispatch</p><h1 className="page-title mt-1">Guardian Circle</h1><p className="muted text-[12px] mt-2">Tier 2 Guardians are private friends and family. They do not appear in responder tools.</p></div><section className="panel p-5 space-y-3"><h2 className="font-bold">Add trusted Guardian</h2><input className="input" placeholder="Full name" value={name} onChange={(event) => setName(event.target.value)} /><input className="input" placeholder="Mobile number" value={phone} onChange={(event) => setPhone(event.target.value)} /><input className="input" placeholder="Relationship" value={relationship} onChange={(event) => setRelationship(event.target.value)} /><button className="btn btn-primary" type="button" onClick={() => void add()}>Add Guardian</button></section><section className="panel"><div className="pane-head"><span>Your Guardians</span><span>{guardians.length}</span></div><div className="p-5 space-y-3">{guardians.map((guardian) => <div className="flex justify-between gap-3" key={guardian.id}><div><b>{guardian.name}</b><p className="muted text-[12px]">{[guardian.relationship, guardian.phone].filter(Boolean).join(" · ") || "Trusted Guardian"}</p></div><button className="btn btn-danger" onClick={() => void remove(guardian.id)}>Remove</button></div>)}{guardians.length === 0 && <p className="muted">No Tier 2 Guardians yet.</p>}{message && <p className="text-[12px] text-[var(--ok)]">{message}</p>}</div></section><section className="panel p-5"><h2 className="font-bold">Tier 1 emergency contact</h2><p className="muted text-[12px] mt-2">Your Tier 1 emergency contact is managed in your profile and is the only personal contact supplied to authorised responders during an alert.</p></section></div>;
}