"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { connectBasteonDevice, type BasteonBleDevice } from "@/lib/ble/basteon";

const failed = (status: string) => status.startsWith("failed:");
const humanStatus = (status: string) => status === "linked" ? "Device linked." : status === "linking" ? "Linking device…" : failed(status) ? `Device rejected linking: ${status.slice(7).replaceAll("_", " ")}.` : status;

export default function LinkDevicePage() {
  const router = useRouter(); const session = useRef<BasteonBleDevice | null>(null); const cleanup = useRef<(() => void) | null>(null);
  const [ready, setReady] = useState(false); const [supported, setSupported] = useState<boolean | null>(null); const [deviceName, setDeviceName] = useState(""); const [deviceId, setDeviceId] = useState(""); const [nickname, setNickname] = useState(""); const [status, setStatus] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { setSupported("bluetooth" in navigator); return () => { cleanup.current?.(); session.current?.disconnect(); }; }, []);
  async function findDevice() { setBusy(true); setError(""); try { const next = await connectBasteonDevice(); session.current?.disconnect(); session.current = next; setDeviceName(next.name); setDeviceId(next.id); setStatus("Device found. Request a linking token when ready."); cleanup.current = next.onStatus((nextStatus) => { setStatus(humanStatus(nextStatus)); if (nextStatus === "linked") { window.setTimeout(() => router.replace("/account/devices"), 900); } }); } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "Could not find device."); } finally { setBusy(false); } }
  async function linkDevice() { if (!session.current || !deviceId) return; setBusy(true); setError(""); try { const response = await fetch("/api/devices/link/start", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ device_id: deviceId, nickname: nickname || undefined }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.replaceAll("_", " ") ?? "Could not start linking."); if (result.already_linked) return router.replace("/account/devices"); setStatus("Sending one-time token to device…"); await session.current.writeToken(result.token); const deadline = Date.now() + 30_000; while (Date.now() < deadline) { await new Promise((resolve) => window.setTimeout(resolve, 2_000)); const devices = await fetch("/api/devices/list"); if (devices.ok && (await devices.json()).some((item: { device_id: string }) => item.device_id === deviceId)) return router.replace("/account/devices"); } throw new Error("The device did not confirm linking. Keep it powered on and try again."); } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "Linking failed."); } finally { setBusy(false); } }
  if (supported === false) return <div className="space-y-4"><h1 className="page-title">Link a device</h1><section className="panel p-4"><p className="font-medium">Web Bluetooth is not available here.</p><p className="muted text-xs mt-2">Use Chrome on Android or Chrome/Edge on a desktop. iPhone, Safari, and Firefox are not supported yet.</p></section></div>;
  return <div className="max-w-xl space-y-4"><div><p className="eyebrow">Bluetooth setup</p><h1 className="page-title mt-1">Link a device</h1></div><section className="panel p-4 space-y-4"><p>Hold the device button while powering it on. The LED will double-blink.</p><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={ready} onChange={(event) => setReady(event.target.checked)} />It&apos;s blinking</label><button className="btn btn-primary w-full !h-10" disabled={!ready || busy} onClick={() => void findDevice()}>{busy && !deviceId ? "Finding device…" : "Find device"}</button><p className="muted text-xs">On Android, turn on Location before scanning. Bluetooth linking requires HTTPS (or localhost).</p></section>{deviceId && <section className="panel p-4 space-y-3"><p className="label">Selected device</p><p className="font-medium">{deviceName}</p><p className="data text-xs muted">{deviceId}</p><label className="block"><span className="label">Nickname <span className="normal-case">(optional)</span></span><input className="input mt-1.5" value={nickname} onChange={(event) => setNickname(event.target.value)} /></label><button className="btn btn-primary w-full !h-10" disabled={busy} onClick={() => void linkDevice()}>{busy ? "Linking…" : "Link this device"}</button>{status && <p role="status" className="text-xs text-[var(--ok)]">{status}</p>}</section>}{error && <section className="panel p-4 border-[var(--crit)]"><p role="alert" className="text-[var(--crit)] text-sm">{error}</p><button className="btn mt-3" onClick={() => { setDeviceId(""); setStatus(""); setError(""); }}>Try again</button></section>}<Link className="btn inline-flex items-center" href="/account/devices">Back to devices</Link></div>;
}