"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Details = { full_name: string; phone: string; home_address: string; emergency_contact_name: string; emergency_contact_phone: string };
const empty: Details = { full_name: "", phone: "", home_address: "", emergency_contact_name: "", emergency_contact_phone: "" };

export default function ProfileInfoPage() {
  const [details, setDetails] = useState<Details>(empty); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [avatarUrl, setAvatarUrl] = useState<string | null>(null);
  useEffect(() => { const db = createClient(); void (async () => { const { data: { user } } = await db.auth.getUser(); if (!user) return; const { data } = await db.from("profiles").select("full_name,phone,home_address,emergency_contact_name,emergency_contact_phone,avatar_path").eq("id", user.id).single(); setDetails({ ...empty, ...data }); if (data?.avatar_path) { const { data: signed } = await db.storage.from("kiki-profile-images").createSignedUrl(data.avatar_path, 3600); setAvatarUrl(signed?.signedUrl ?? null); } })(); }, []);
  function field(key: keyof Details) { return { value: details[key], onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setDetails((current) => ({ ...current, [key]: event.target.value })) }; }
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); const db = createClient(); const { data: { user } } = await db.auth.getUser(); if (user) { const { error } = await db.from("profiles").update({ ...details, full_name: details.full_name.trim(), phone: details.phone.trim() || null, home_address: details.home_address.trim() || null, emergency_contact_name: details.emergency_contact_name.trim() || null, emergency_contact_phone: details.emergency_contact_phone.trim() || null }).eq("id", user.id); setMessage(error?.message ?? "Profile details saved."); } setSaving(false); }
  async function uploadAvatar(file: File | undefined) { if (!file) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 2 * 1024 * 1024) return setMessage("Choose a JPG, PNG, or WebP image smaller than 2 MB."); const db = createClient(); const { data: { user } } = await db.auth.getUser(); if (!user) return; const extension = file.name.split(".").pop()?.replace(/[^a-z0-9]/gi, "") || "jpg"; const path = `${user.id}/avatar.${extension}`; const { error: uploadError } = await db.storage.from("kiki-profile-images").upload(path, file, { upsert: true, contentType: file.type }); const { error } = uploadError ? { error: uploadError } : await db.from("profiles").update({ avatar_path: path }).eq("id", user.id); if (error) return setMessage(error.message); const { data: signed } = await db.storage.from("kiki-profile-images").createSignedUrl(path, 3600); setAvatarUrl(signed?.signedUrl ?? null); setMessage("Profile image saved."); }
  return <form className="kiki-setting-page" onSubmit={save}><header><span>MY ACCOUNT</span><h1>Personal details</h1><p>Keep your identity and emergency contact information current.</p></header><section><label className="kiki-avatar-upload">{avatarUrl ? <img src={avatarUrl} alt="Your profile" /> : <span>{details.full_name.trim().charAt(0).toUpperCase() || "K"}</span>}<b>Profile image<small>JPG, PNG, or WebP · up to 2 MB</small></b><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void uploadAvatar(event.target.files?.[0])} /></label><label>Full name<input className="input" required {...field("full_name")} /></label><label>Mobile number<input className="input" type="tel" {...field("phone")} /></label><label>Home address<textarea className="input" {...field("home_address")} /></label><label>Emergency contact name<input className="input" {...field("emergency_contact_name")} /></label><label>Emergency contact phone<input className="input" type="tel" {...field("emergency_contact_phone")} /></label>{message && <p role="status">{message}</p>}<button className="btn btn-primary" disabled={saving}>{saving ? "Saving..." : "Save details"}</button></section></form>;
}
