"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, LocateFixed, MapPin, ThumbsUp } from "lucide-react";
import { categoryLabel, currentMeetingLocation, meetingFetch, type CommunityAlert } from "@/lib/buddies/meeting/client";

type Place = { label: string; lat: number; lng: number };
type Props = { alerts: CommunityAlert[]; busy: boolean; onBusyChange: (busy: boolean) => void; onAlertsChange: (alerts: CommunityAlert[]) => void; onLocationChange: (point: { lat: number; lng: number } | null) => void; onMessage: (message: string) => void };
const concerns = ["unsafe_area", "poor_lighting", "harassment", "road_hazard"];

export function CommunityAlertsPanel({ alerts, busy, onBusyChange, onAlertsChange, onLocationChange, onMessage }: Props) {
  const [kind, setKind] = useState("unsafe_area"); const [detail, setDetail] = useState(""); const [address, setAddress] = useState(""); const [suggestions, setSuggestions] = useState<Place[]>([]); const [location, setLocation] = useState<Place | null>(null);
  useEffect(() => { if (address.trim().length < 3 || location?.label === address) { setSuggestions([]); return; } const controller = new AbortController(); const timer = window.setTimeout(() => { void fetch("/api/trips/geocode", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query: address }), signal: controller.signal }).then(async (response) => response.ok ? response.json() as Promise<Place[]> : []).then((places) => { if (!controller.signal.aborted) setSuggestions(places); }).catch(() => undefined); }, 300); return () => { controller.abort(); window.clearTimeout(timer); }; }, [address, location?.label]);
  function choose(place: Place) { setLocation(place); setAddress(place.label); setSuggestions([]); onLocationChange({ lat: place.lat, lng: place.lng }); }
  async function useCurrentLocation() { onBusyChange(true); try { const point = await currentMeetingLocation(); choose({ ...point, label: "Current location" }); onMessage("Location added to your report."); } catch (error) { onMessage(error instanceof Error ? error.message : "Location could not be shared."); } finally { onBusyChange(false); } }
  async function submit() { if (!location || detail.trim().length < 4) return; onBusyChange(true); try { await meetingFetch("/api/buddies/community-alerts", { kind, lat: location.lat, lng: location.lng, locationLabel: location.label, detail: detail.trim() }); const query = new URLSearchParams({ lat: String(location.lat), lng: String(location.lng) }); const data = await meetingFetch<{ alerts: CommunityAlert[] }>(`/api/buddies/community-alerts?${query}`); onAlertsChange(data.alerts); onMessage("Your community report is now visible to people nearby."); setDetail(""); } catch (error) { onMessage(error instanceof Error ? error.message : "Could not submit that report."); } finally { onBusyChange(false); } }
  async function vote(alert: CommunityAlert) { onBusyChange(true); try { const result = await meetingFetch<{ voted: boolean; upvotes: number }>(`/api/buddies/community-alerts/${alert.id}/vote`, {}); onAlertsChange(alerts.map((item) => item.id === alert.id ? { ...item, voted: result.voted, upvotes: result.upvotes } : item)); } catch (error) { onMessage(error instanceof Error ? error.message : "Could not update your confirmation."); } finally { onBusyChange(false); } }
  return <section id="community-alerts" className="buddies-panel buddy-community-panel"><div className="buddy-community-heading"><div><h2><AlertTriangle size={18} />Community alerts</h2><p>Local reports from people in your area.</p></div></div><div className="buddy-report-form"><label className="field">Concern<select value={kind} onChange={(event) => setKind(event.target.value)}>{concerns.map((value) => <option key={value} value={value}>{categoryLabel(value)}</option>)}</select></label><label className="field buddy-report-location">Location<div className="buddy-location-row"><input value={address} onChange={(event) => { setAddress(event.target.value); setLocation(null); }} placeholder="Search an address" autoComplete="off" /><button type="button" className="btn" disabled={busy} onClick={() => void useCurrentLocation()}><LocateFixed size={16} />Use mine</button></div>{suggestions.length > 0 && <div className="buddy-address-results">{suggestions.map((place) => <button type="button" key={`${place.lat}-${place.lng}`} onClick={() => choose(place)}><MapPin size={15} />{place.label}</button>)}</div>}{location && <small className="buddy-location-selected"><MapPin size={14} />{location.label}</small>}</label><label className="field">What happened?<textarea value={detail} maxLength={500} onChange={(event) => setDetail(event.target.value)} placeholder="A short description helps others understand the concern." /></label><button className="btn btn-primary" disabled={busy || !location || detail.trim().length < 4} onClick={() => void submit()}><AlertTriangle size={16} />Share local report</button></div><div className="buddy-alert-list">{alerts.filter((alert) => Date.parse(alert.expires_at) > Date.now()).map((alert) => <article key={alert.id} className="buddy-alert-card"><div className="buddy-alert-copy"><b>{categoryLabel(alert.kind)}</b><p>{alert.detail ?? "Community report"}</p><small><MapPin size={13} />{alert.location_label ?? "Nearby location"} · expires {new Date(alert.expires_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</small></div><button className={`buddy-upvote ${alert.voted ? "is-voted" : ""}`} type="button" disabled={busy} onClick={() => void vote(alert)} aria-pressed={alert.voted}><ThumbsUp size={16} /><span>{alert.upvotes}</span></button></article>)}</div>{alerts.length === 0 && <p className="buddy-alert-empty">No active reports near this location.</p>}</section>;
}