"use client";

import { Fragment, useState } from "react";
import { fmtDateTime, fmtRelativeTime } from "@/lib/datetime";
import type { Profile } from "@/lib/types";

export function UserTable({ users, refresh }: { users: Profile[]; refresh(): void }) {
	const [expanded, setExpanded] = useState<string | null>(null);
	async function role(id: string, value: string) { await fetch("/api/admin/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, role: value }) }); void refresh(); }
	return <div className="tbl-wrap"><table className="tbl"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Role</th><th>Linked devices</th><th>Created</th></tr></thead><tbody>{users.map((user) => { const incomplete = !user.full_name?.trim() || !user.phone?.trim(); const open = expanded === user.id; return <Fragment key={user.id}><tr><td>{user.full_name ?? "—"}{incomplete && <span className="status status-amber ml-2">Profile incomplete</span>}</td><td className="muted">{user.email ?? "—"}</td><td className="data muted">{user.phone ?? "—"}</td><td><select className="input !w-28 !py-1" value={user.role} onChange={(event) => void role(user.id, event.target.value)}>{["admin", "responder", "user"].map((roleName) => <option key={roleName}>{roleName}</option>)}</select></td><td><button className="btn !px-2 data" disabled={!user.linked_device_count} onClick={() => setExpanded(open ? null : user.id)}>{user.linked_device_count ?? 0}</button></td><td className="data muted">{fmtDateTime(user.created_at)}</td></tr>{open && <tr><td colSpan={6} className="!p-3"><div className="border border-[var(--line)] bg-[var(--bg)] p-3"><p className="label mb-2">Linked devices</p><div className="space-y-2">{(user.devices ?? []).map((device) => <div key={device.id} className="flex flex-wrap items-center justify-between gap-2 text-xs"><span><b>{device.device_name}</b> <span className="data muted ml-2">{device.device_id}</span></span><span className={`status ${device.active ? "status-green" : "status-gray"}`}>{device.active ? "Active" : "Inactive"}</span><span className="muted" title={device.last_seen_at ? fmtDateTime(device.last_seen_at) : undefined}>{device.last_seen_at ? fmtRelativeTime(device.last_seen_at) : "Never seen"}</span></div>)}</div></div></td></tr>}</Fragment>; })}</tbody></table></div>;
}